-- Sample whiskey data for testing
INSERT INTO whiskeys (name, brand, distillery, type, region, age, abv, description, image_url) VALUES
('Lagavulin 16', 'Lagavulin', 'Lagavulin Distillery', 'single_malt', 'islay', 16, 43.0, 'A classic Islay single malt with rich peat smoke and maritime character. Notes of iodine, seaweed, and bonfire smoke.', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400'),
('Macallan 18', 'Macallan', 'Macallan Distillery', 'single_malt', 'speyside', 18, 43.0, 'A luxurious Speyside single malt with notes of dried fruit, spice, and oak. Rich and complex with a long finish.', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400'),
('Woodford Reserve', 'Woodford Reserve', 'Woodford Reserve Distillery', 'bourbon', 'kentucky', NULL, 45.2, 'A premium Kentucky bourbon with rich, complex flavors of vanilla, caramel, and spice. Smooth and well-balanced.', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400'),
('Glenfiddich 12', 'Glenfiddich', 'Glenfiddich Distillery', 'single_malt', 'speyside', 12, 40.0, 'A classic Speyside single malt with notes of pear, apple, and oak. Light and approachable.', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400'),
('Jameson', 'Jameson', 'Midleton Distillery', 'blended_whiskey', 'ireland', NULL, 40.0, 'Ireland''s most popular whiskey. Smooth and mellow with notes of vanilla, honey, and light spice.', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400'),
('Hibiki 17', 'Hibiki', 'Yamazaki Distillery', 'blended_whiskey', 'japan', 17, 43.0, 'A premium Japanese blended whiskey with exceptional balance and harmony. Notes of rose, lychee, and sandalwood.', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400'),
('Ardbeg 10', 'Ardbeg', 'Ardbeg Distillery', 'single_malt', 'islay', 10, 46.0, 'An intensely peated Islay single malt with notes of smoke, citrus, and vanilla. Bold and uncompromising.', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400'),
('Crown Royal', 'Crown Royal', 'Gimli Distillery', 'blended_whiskey', 'canada', NULL, 40.0, 'A smooth Canadian blended whiskey with notes of vanilla, oak, and light fruit. Easy-drinking and versatile.', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400'),
('Bulleit Bourbon', 'Bulleit', 'Four Roses Distillery', 'bourbon', 'kentucky', NULL, 45.0, 'A high-rye bourbon with bold, spicy flavors. Notes of vanilla, oak, and pepper with a long, smooth finish.', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400'),
('Talisker 10', 'Talisker', 'Talisker Distillery', 'single_malt', 'islands', 10, 45.8, 'A maritime single malt from the Isle of Skye. Notes of sea salt, pepper, and smoke with a distinctive coastal character.', 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400');
